### ISSUE TITLE
import pygame sys error :( 

### ISSUE THREAD

**Issue by uzairleo** [rainnic/python-scripts#1]
i have all libraries and package of python 3 but still it showing error to me 
here is the pic
![reminder](https://user-images.githubusercontent.com/52172428/74385377-3b09d000-4e15-11ea-8671-c79b664cf23d.png)

**Comment by rainnic** [comment]
Hi, you have to install the module named 'pygame' in order to execute my
script. You can solve in two manners:
1) sudo apt-get install python-pygame
2) pip install Pygame

Yours sincerely,
Nicola
    Rainnic in the Clouds
 Working from scratch, following simplicity
   \\--->  rainnic.altervista.org  <---//


Il giorno mer 12 feb 2020 alle ore 23:59 Uzair Leo <notifications@github.com>
ha scritto:

**Comment by uzairleo** [comment]
i install everything but still issue of this module coming whenever i run ur program using terminal :(
